package com.webbyit.swing;

import java.awt.Color;
import javax.swing.JComponent;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * A demo frame just to highlight the functionality provided in the modality
 * demo.
 *
 * @author webbit
 *
 */
public class DemoModalityFrame extends ModalityInternalFrame {

    public DemoModalityFrame() {
        initComponents();
    }

    private void setColor() {
        if (parent != null && parent instanceof DemoModalityFrame) {
            iconLabel.setOpaque(true);
            iconLabel.setBackground(((DemoModalityFrame) parent).getIconLabel().getBackground());
        } else {
            int r = (int) (Math.random() * 255);
            int g = (int) (Math.random() * 255);
            int b = (int) (Math.random() * 255);
            iconLabel.setOpaque(true);
            iconLabel.setBackground(new Color(r, g, b));
        }
    }

    protected JLabel getIconLabel() {
        return iconLabel;
    }

    public DemoModalityFrame(JComponent parentFrame) {
        this(parentFrame, null);
    }

    public DemoModalityFrame(JComponent parentFrame, String title) {
        this(parentFrame, title, false);
    }

    public DemoModalityFrame(JComponent parentFrame, String title, boolean resizable) {
        this(parentFrame, title, resizable, false);
    }

    public DemoModalityFrame(JComponent parentFrame, String title, boolean resizable, boolean closeable) {
        this(parentFrame, title, resizable, closeable, false);
    }

    public DemoModalityFrame(JComponent parentFrame, String title, boolean resizable, boolean closeable,
                             boolean maximizable) {
        this(parentFrame, title, resizable, closeable, maximizable, false);
    }

    public DemoModalityFrame(JComponent parentFrame, String title, boolean resizable, boolean closeable,
                             boolean maximizable, boolean iconifiable) {
        super(parentFrame, title, resizable, closeable, maximizable, iconifiable);
        setColor();
    }

    protected void init() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        childModalFrameBtn = new javax.swing.JButton();
        iconLabel = new javax.swing.JLabel();
        desktopModalDialogBtn = new javax.swing.JButton();
        childModalDialogBtn = new javax.swing.JButton();

        childModalFrameBtn.setText("Create Child Modal Frame");
        childModalFrameBtn.setActionCommand("Create Modal Frame");
        childModalFrameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                childModalFrameBtnActionPerformed(evt);
            }
        });

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/webbyit/swing/scream.jpg"))); // NOI18N

        desktopModalDialogBtn.setText("Create Desktop Modal Dialog");
        desktopModalDialogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desktopModalDialogBtnActionPerformed(evt);
            }
        });

        childModalDialogBtn.setText("Create Child Modal Dialog");
        childModalDialogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                childModalDialogBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(childModalFrameBtn)
                    .addComponent(childModalDialogBtn)
                    .addComponent(desktopModalDialogBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {childModalDialogBtn, childModalFrameBtn, desktopModalDialogBtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(iconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(childModalFrameBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(childModalDialogBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(desktopModalDialogBtn)
                        .addGap(100, 100, 100))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void childModalFrameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_childModalFrameBtnActionPerformed
        ModalityInternalFrame newFrame = new DemoModalityFrame(this, "child", true, true, true, true);
        JDesktopPane desktop = JOptionPane.getDesktopPaneForComponent(this);
//        int xRand = (int) (Math.random() * 100);
//        int yRand = (int) (Math.random() * 100);
//        newFrame.setBounds(30, 30, 350 + xRand, 200 + yRand);

        desktop.add(newFrame);
        newFrame.show();
    }//GEN-LAST:event_childModalFrameBtnActionPerformed

    private void desktopModalDialogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desktopModalDialogBtnActionPerformed
        JOptionPane.showInternalMessageDialog(this, "The desktop is now locked!", "Modal Message",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_desktopModalDialogBtnActionPerformed

    private void childModalDialogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_childModalDialogBtnActionPerformed
        JOptionPane pane = new JOptionPane("I've errored", JOptionPane.ERROR_MESSAGE, JOptionPane.OK_OPTION);
        ModalityInternalOptionFrame optionFrame = new ModalityInternalOptionFrame(this, pane, "Error dialog");
        JDesktopPane desktop = JOptionPane.getDesktopPaneForComponent(this);
        desktop.add(optionFrame);
        optionFrame.show();
    }//GEN-LAST:event_childModalDialogBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton childModalDialogBtn;
    private javax.swing.JButton childModalFrameBtn;
    private javax.swing.JButton desktopModalDialogBtn;
    private javax.swing.JLabel iconLabel;
    // End of variables declaration//GEN-END:variables
}
